FROM alpine:latest

# RUN useradd bVasquez

# USER bVasquez

# Variable de entorno.
ENV DEMO = Hola

CMD whoami
# RUN apt -y update && apt install iputils-ping

# CMD echo $DEMO World
# CMD ping 127.0.0.1

# Construir una imagen llamada mydemo:v1.0.0
# Tomando como referencia la carpeta demo.
## docker build -t mydemo:v1.0.0 containers/demo/

# Cada vez que se hace un cambio, se debe actualizar la imagen y cambiar su version.

# Ver todas los contenedores o instancias:
## docker ps -a

# Modificar la variable de entorno en el comando
## docker run -e DEMO=Yazmin my demo:v1.0.2

# Creand un container

